# Generated by Django 4.2.13 on 2024-10-02 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowers', to='core.faction')),
                ('known', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known', to='core.faction')),
            ],
        ),
    ]
