# Generated by Django 4.2.13 on 2024-10-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_factionknowledge_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionknowledge',
            name='known',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowns', to='core.faction'),
        ),
    ]
